export const LOGIN_LOADER = "LOGIN_LOADER"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER_LOADER = "REGISTER_LOADER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const USERS_LOADER = "USERS_LOADER"
export const USERS_SUCCESS = "USERS_SUCCESS"
export const USERS_FAILED = "USERS_FAILED"

export const UPDATE_USERS_LOADER = "UPDATE_USERS_LOADER"
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS"
export const UPDATE_USERS_FAILED = "UPDATE_USERS_FAILED"

export const LOCATION_LOADER = "LOCATION_LOADER"
export const LOCATION_SUCCESS = "LOCATION_SUCCESS"
export const LOCATION_FAILED = "LOCATION_FAILED"

export const DELETE_LOCATION_LOADER = "DELETE_LOCATION_LOADER"
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS"
export const DELETE_LOCATION_FAILED = "DELETE_LOCATION_FAILED"